name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # IOS
  cupertino_icons: ^1.0.4

  # FIREBASE
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  firebase_messaging: ^11.2.5
  firebase_crashlytics: ^2.4.5
  firebase_performance: ^0.8.0+4
  firebase_app_check: ^0.0.6+4

  # ARCHITECTURE
  flutter_bloc: ^8.0.1

  # MODEL
  equatable: ^2.0.3
  uuid: ^3.0.5

  # OTHERS
  timelines: ^0.1.0

dev_dependencies:
  test: ^1.20.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/